# fly.toml app configuration file generated for day88-catholic-young-adults-autumn-cherry-2277 on 2025-07-27T18:01:26-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'day88-catholic-young-adults-autumn-cherry-2277'
primary_region = 'bos'

[build]
  dockerfile = './Dockerfile'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
