app = "day88-catholic-young-adults-autumn-cherry-2277"
primary_region = "bos"

[build]
  dockerfile = "./Dockerfile"

[deploy]
  release_command = "bash -lc 'cd /app && source .venv/bin/activate && flask db upgrade'"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[[mounts]]
  source = "data_volume"
  destination = "/data"

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  auto_stop_machines = false     # keep machine running
  min_machines_running = 1
  processes = ["app"]

  [[http_service.checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
    method = "GET"
    path = "/healthz"
    protocol = "http"
