# fly.toml app configuration file generated for day88-catholic-young-adults-white-feather-8386 on 2025-07-14T21:35:49-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'day88-catholic-young-adults-white-feather-8386'
primary_region = 'bos'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
