"""Add approximate_age_range to Catholic

Revision ID: 321d0f9577f6
Revises: 3bac908fb914
Create Date: 2025-08-07 18:51:24.098478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '321d0f9577f6'
down_revision = '3bac908fb914'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catholic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approximate_age_range', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catholic', schema=None) as batch_op:
        batch_op.drop_column('approximate_age_range')

    # ### end Alembic commands ###
