"""Add recurring fields to Event model

Revision ID: 6b60db82a628
Revises: 8d1f4b737079
Create Date: 2025-08-04 11:39:50.997794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b60db82a628'
down_revision = '8d1f4b737079'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_recurring', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('recurring_day', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('recurring_week', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('recurring_time', sa.String(length=10), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('date_time',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('group_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('link')
        batch_op.drop_column('zip_code')
        batch_op.drop_column('status')
        batch_op.drop_column('address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('zip_code', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('link', sa.VARCHAR(length=300), nullable=True))
        batch_op.alter_column('group_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('date_time',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.drop_column('recurring_time')
        batch_op.drop_column('recurring_week')
        batch_op.drop_column('recurring_day')
        batch_op.drop_column('is_recurring')

    # ### end Alembic commands ###
